# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "af4bc9d1669e3e5b1a719231f23cd4fa"
name = "kopy Products"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# Kopy Products nécessite ces scopes pour :
# - read_products : lire les produits sources
# - write_products : créer/modifier les produits dans la boutique destination
# - read_orders : pour les statistiques et insights (futur)
scopes = "write_products,read_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
